[target.'cfg(all(not(target_arch = "wasm32"), not(feature = "noconfig")))']
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    # LLD is generally faster and might be the default for Rust in the future.
    # See here: https://github.com/rust-lang/rust/issues/71515
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "target-cpu=native"
]
